apiVersion: v2
name: openshift-102-workshop
description: Static OpenShift 102 workshop (Antora showroom) served over HTTP
type: application
version: 1.0.12
appVersion: "v1.0.12"
keywords:
  - openshift
  - workshop
  - antora
maintainers:
  - name: maintainers
