{{- if and .Values.route.enabled (.Capabilities.APIVersions.Has "route.openshift.io/v1") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "workshop.fullname" . }}
  labels:
    helm.sh/chart: {{ include "workshop.chart" . }}
    app.kubernetes.io/name: {{ include "workshop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "workshop.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.termination }}
{{- end }}
